#!/bin/bash
#
#    Version:        2017.04
#    Authors:        sysadmin@vhalholl.info
#    Description:    install vim-apthogen from github
#    Dependencies:   git

vCurentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
vLogFile="$vCurentDir/.infection-$(date +%Y%m%d).log"

if [[ ! -z "$(which git)" ]];
then
    # Create Directories
    [[ ! -d "$vCurentDir/bundle" ]]&&  mkdir "$vCurentDir/bundle"
    [[ ! -d "$vCurentDir/bundle-available" ]]&&  mkdir "$vCurentDir/bundle-available"
    [[ ! -d "$vCurentDir/bundle-available/vim-apthogen" ]]&& {
        echo "Apthogen::Incubate"
        git clone https://github.com/vhalholl/vim-apthogen "$vCurentDir/bundle-available/vim-apthogen" &>"$vLogFile"
    }
    # Make Initials Symlinks, apthogen will handles them by himself later
    [[ ! -L "$vCurentDir/bundle/vim-apthogen" ]]&&{
        echo "Apthogen::Infection"
        ln -s "$vCurentDir/bundle-available/vim-apthogen" "$vCurentDir/bundle/"
        ln -s "$vCurentDir/bundle-available/vim-apthogen/apthogen" ./
        ln -s "$vCurentDir/bundle-available/vim-apthogen/infection" ./
        ln -s "$vCurentDir/bundle-available/vim-apthogen/adn" ./
        ln -s "$vCurentDir/bundle-available/vim-apthogen/mutations" ./
        ln -s "$vCurentDir/bundle-available/vim-apthogen/.vimrc" ./
        ln -s "$vCurentDir/bundle-available/vim-apthogen/plugin" ./config
    }

    fModuleListImport(){
        echo "Apthogen::Propagate::$1"
        while read -r line;do
            "$vCurentDir/apthogen" import "$line"
        done < "$vCurentDir/mutations/.$1.list"
    }

    #TODO: Best package integration, More Flavor like 

    read -r -p "Propagate :
    [S]lim               (Only Required Modules)     
    [M]inimal            (Default)
    [H]ighly Recomended  
    [R]ecomended          
    [W]hynot             
    [A]ll                (Not Recomended For Testing Purpose)
    [C]ancel
    Enter your choice and press [Enter]:   " c
    case "$c" in 
        a|A)    echo "Propagate::All ($(wc -l < "$vCurentDir/adn/.apthogen.list") Modules)";./apthogen import all;;
        c|C)    exit 0 ;;
        s|S)    fModuleListImport required ;;
        h|H)    fModuleListImport minimal; fModuleListImport highly ;;
        r|R)    fModuleListImport highly; fModuleListImport recomended ;;
        w|W)    fModuleListImport recomended; fModuleListImport whynot ;;
        *)      fModuleListImport required; fModuleListImport minimal ;;
    esac
else 
    echo "Command git not found ! Try : sudo apt install git";
    exit 0; 
fi
