#!/bin/bash
: << 'install.sh'
    Version: 2016.04
    Authors: sysadmin@vhalholl.info
    Description: install apthogen from github
    Dependencies: git
install.sh

CDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOGS="$CDIR/.install-log-$(date +%Y%m%d)"

DEP=$(which git);[ ! -z $DEP ]&& {

    #echo "Creating Directories"
    [[ ! -d $CDIR/bundle ]]&&  mkdir $CDIR/bundle
    [[ ! -d $CDIR/bundle-availlable ]]&&  mkdir $CDIR/bundle-availlable
    [[ ! -d $CDIR/bundle-availlable/vim-apthogen ]]&& {
        echo "Apthogen::Incubate"
        cd $CDIR/bundle-availlable
        git clone https://github.com/vhalholl/vim-apthogen &>$LOGS
        cd ..
    }
    [[ ! -L $CDIR/bundle/vim-apthogen ]]&&{
        echo "Apthogen::Infection"
        ln -s $CDIR/bundle-availlable/vim-apthogen $CDIR/bundle/
        ln -s $CDIR/bundle-availlable/vim-apthogen/.modulelist ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/netinstall ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/templates ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/apthogen ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.vimrc ./ 
    }

    n=$(cat $CDIR/.modulelist |wc -l)
    _import_required(){
        echo "Propagate::Required";
        for i in {vim-pathogen,vim-sensible,vim-project,vim-togglemouse,vimproc.vim,vimshell.vim,vim-delimitMat,vim-rooter};do ./apthogen import $i; done
    }
    _import_highly(){
        _import_required
        echo "Propagate::Highly"
        for i in {vim-eunuch,vim-fugitive,vim-airline,vim-signify,nerdtree,syntastic,git-vim,puppet-eyes,tagbar,taglist.vim,taskList.vim};do ./apthogen import $i; done
    }
    _import_recomended(){
        _import_highly
        echo "Propagate::Recomended"
        for i in {vim-gitolite,puppet-syntax-vim,phpcomplete.vim,python-mode,vim-virtualenv,vim-perl,vim-ruby,vim-varnish,vim-html5};do ./apthogen import $i; done
    }
    _import_whynot(){
        _import_recomended
        echo "Propagate::Whynot"
        for i in {vim-powerline,vdebug,vim-colorschemes,TeTrIs.vim};do ./apthogen import $i; done
    }

    read -p "Propagate :
[M]inimal (Default)
[H]ighly Recomended
[R]ecomended
[W]hynot
[A]ll (May take a while)
[C]ancel
Enter your choice and press [Enter]:   " c
    case "$c" in 
        a|A)    echo "Propagate::All ($n)"; ./apthogen import ;;
        c|C)    exit 0 ;;
        h|H)    _import_highly ;;
        r|R)    _import_recomended ;;
        w|W)    _import_whynot ;;
        *)      _import_required ;;
    esac
}||{ echo "Command git not found ! Try : sudo apt install git";exit 0; }
