#!/bin/bash
: << 'install.sh'
    Version: 2016.04
    Authors: sysadmin@vhalholl.info
    Description: install apthogen from github
    Dependencies: git
install.sh

CDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOGS="$CDIR/.netinstall-$(date +%Y%m%d).log"

DEP=$(which git);[ ! -z $DEP ]&& {

    [[ ! -d $CDIR/bundle ]]&&  mkdir $CDIR/bundle
    [[ ! -d $CDIR/bundle-availlable ]]&&  mkdir $CDIR/bundle-availlable
    [[ ! -d $CDIR/bundle-availlable/vim-apthogen ]]&& {
        echo "Apthogen::Incubate"
        cd $CDIR/bundle-availlable
        git clone https://github.com/vhalholl/vim-apthogen &>$LOGS
        cd ..
    }
    [[ ! -L $CDIR/bundle/vim-apthogen ]]&&{
        echo "Apthogen::Infection"
        ln -s $CDIR/bundle-availlable/vim-apthogen $CDIR/bundle/
        ln -s $CDIR/bundle-availlable/vim-apthogen/apthogen ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/netinstall ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.apthogen.list ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.vimrc ./
        
        ln -s $CDIR/bundle-availlable/vim-apthogen/templates ./

        ln -s $CDIR/bundle-availlable/vim-apthogen/.required.list ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.minimal.list ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.highly.list ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.recomended.list ./
        ln -s $CDIR/bundle-availlable/vim-apthogen/.whynot.list ./
    }

    n=$(cat $CDIR/.apthogen.list |wc -l)

    _import(){
        echo "Propagate::$1"
        while read -r line;do
            ./apthogen import $line
        done < .$1.list
    }

    read -p "Propagate :
[S]lim               (Only Required Modules)     
[M]inimal            (Default)
[H]ighly Recomended  
[R]ecomended          
[W]hynot             
[A]ll                (Not Recomended For Testing Purpose)
[C]ancel
Enter your choice and press [Enter]:   " c
    case "$c" in 
        a|A)    echo "Propagate::All ($n)"; ./apthogen import ;;
        c|C)    exit 0 ;;
        s|S)    _import required ;;
        h|H)    _import minimal; _import highly ;;
        r|R)    _import highly; _import recomended ;;
        w|W)    _import recomended; _import whynot ;;
        *)      _import required; _import minimal ;;
    esac
}||{ echo "Command git not found ! Try : sudo apt install git";exit 0; }
